version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: todo_master
      POSTGRES_PASSWORD: todo_pwd
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/

volumes:
  postgres-data: